### GET request to example server

POST {{host}}/notes
Content-Type: application/json

{
  "content": "Hello World",
  "attachment": "hello.jpg"
}

###
GET {{host}}/notes/eac9fb50-42ee-11ef-b552-03be4da37d81

###

###

GET {{host}}/notes
###

###
PUT {{host}}/notes/73517890-43b7-11ef-8045-db3ae0805ccb
Content-Type: application/json

{
  "content": "TEST-New World",
  "attachment": "TEST-new.jpg"
}
###

###
DELETE {{host}}/notes/7a1298d0-43b7-11ef-8045-db3ae0805ccb

###


